# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

# Required in golangci-lint v2+
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - unparam
    - dogsled
    - nakedret
    - prealloc
    - gocritic
    - funlen
    - whitespace

  disable:
    - dupl
    - gocyclo
    - lll
    - gocognit
    - goconst
    - depguard
    - godot  # Too strict about comment formatting

linters-settings:
  govet:
    check-shadowing: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50
    # Ignore test functions
    ignore-comments: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - funlen

    - path: pkg/version/
      linters:
        - gochecknoglobals

    - path: cmd/
      linters:
        - gochecknoglobals

    - text: "do not define dynamic errors"
      linters:
        - goerr113

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false