global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mirror'
    static_configs:
      - targets: ['mirror:9090']
        labels:
          service: 'mirror-streaming'
          
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'redis'
