# Default configuration for Mirror streaming server

server:
  http3_port: 443
  tls_cert_file: "./certs/cert.pem"
  tls_key_file: "./certs/key.pem"
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 10s
  max_incoming_streams: 5000
  max_incoming_uni_streams: 1000
  max_idle_timeout: 30s

redis:
  addresses:
    - "localhost:6379"
  password: ""
  db: 0
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_size: 100
  min_idle_conns: 10

logging:
  level: "info"
  format: "json"
  output: "stdout"
  max_size: 100    # MB
  max_backups: 5
  max_age: 30      # days

metrics:
  enabled: true
  path: "/metrics"
  port: 9090

ingestion:
  queue_dir: "/tmp/mirror/queue"  # Directory for queue overflow to disk
  srt:
    enabled: true
    listen_addr: "0.0.0.0"
    port: 1234
    latency: 120ms         # SRT latency window
    max_bandwidth: 52428800  # 50 Mbps - maximum allowed bandwidth per stream
    input_bandwidth: 52428800  # 50 Mbps - expected input rate for buffer sizing
    payload_size: 1316     # MTU-friendly payload size
    fc_window: 25600       # Flow control window size
    peer_idle_timeout: 5s  # Peer idle timeout
    max_connections: 25    # Maximum concurrent connections
    encryption:
      enabled: false
      passphrase: ""
      key_length: 128      # 0 (auto), 128, 192, or 256
      pbkdf_iterations: 0  # 0 for auto
  rtp:
    enabled: true
    listen_addr: "0.0.0.0"
    port: 5004
    rtcp_port: 5005
    buffer_size: 65536       # 64KB receive buffer
    max_sessions: 25         # Maximum concurrent RTP sessions
    session_timeout: 10s     # Session idle timeout
  buffer:
    ring_size: 4194304     # 4MB per stream (temporary - will be replaced by dynamic)
    pool_size: 50          # Should be >= total max connections (SRT: 25 + RTP: 25)
    write_timeout: 10ms
    read_timeout: 10ms
    metrics_enabled: true
    default_bitrate: 52428800  # 50 Mbps default
    target_duration: 30s   # 30 seconds of buffer
  registry:
    redis_addr: "localhost:6379"
    redis_password: ""
    redis_db: 0
    ttl: 1h
  memory:
    max_total: 2684354560      # 2.5GB total memory limit
    max_per_stream: 209715200  # 200MB per stream limit
  
  # Stream handling configuration
  stream_handling:
    frame_assembly_timeout: 200ms  # Timeout for frame assembly
    gop_buffer_size: 3            # Number of GOPs to buffer per stream
    max_gop_age: 5s               # Maximum age of GOP before cleanup
    error_retry_limit: 3          # Maximum retries for stream errors
  
  # Backpressure control configuration
  backpressure:
    enabled: true                 # Enable backpressure control
    low_watermark: 0.25          # Low pressure threshold (25%)
    medium_watermark: 0.5        # Medium pressure threshold (50%)
    high_watermark: 0.75         # High pressure threshold (75%)
    critical_watermark: 0.9      # Critical pressure threshold (90%)
    response_window: 500ms       # Response time window for pressure changes
    frame_drop_ratio: 0.1        # Percentage of frames to drop under pressure (10%)
