# Development configuration for Mirror streaming server
# This overrides values from default.yaml

server:
  http3_port: 8443
  tls_cert_file: "./certs/dev-cert.pem"
  tls_key_file: "./certs/dev-key.pem"
  read_timeout: 60s
  write_timeout: 60s
  shutdown_timeout: 5s
  max_incoming_streams: 1000
  max_incoming_uni_streams: 500
  max_idle_timeout: 60s

redis:
  addresses:
    - "localhost:6379"
  password: ""
  db: 0
  max_retries: 5
  dial_timeout: 10s
  read_timeout: 5s
  write_timeout: 5s
  pool_size: 50
  min_idle_conns: 5

logging:
  level: "debug"
  format: "text"
  output: "stdout"
  max_size: 50     # MB
  max_backups: 3
  max_age: 7       # days

metrics:
  enabled: true
  path: "/metrics"
  port: 9091

ingestion:
  queue_dir: "./data/queue"  # Local directory for development
  srt:
    enabled: true
    max_bandwidth: 52428800  # 50 Mbps
    encryption:
      enabled: false  # Enable for testing encryption
      passphrase: ""  # Set via MIRROR_INGESTION_SRT_ENCRYPTION_PASSPHRASE
      key_length: 256  # 0 (auto), 128, 192, or 256
      pbkdf_iterations: 0  # 0 for auto
  rtp:
    enabled: true
    max_bandwidth: 52428800  # 50 Mbps
  codecs:
    supported: ["HEVC", "H264", "AV1", "JPEGXS"]
    preferred: "HEVC"
    h264:
      profiles: ["baseline", "main", "high"]
      level: "5.1"
    hevc:
      profiles: ["main", "main10"]
      level: "5.1"
    av1:
      profile: "0"  # Main profile
      level: "5.1"
    jpegxs:
      profile: "main"
      subsampling: "422"
  memory:
    max_total: 8589934592      # 8GB for development (matching production for testing)
    max_per_stream: 419430400  # 400MB per stream for development
